import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import { GeneralContext } from '../Context/GeneralContext';


import Link from 'next/link'

export default function Home() {

  const title = GeneralContext();

  useEffect(() => {
    title.setTitle("home");
  })



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a> Black sheep</a>
        </h1>

        <p className={styles.description}>
          upcoming events /


          <Link href="Members">
            <a>artists</a>
          </Link>


          / archive/
        </p>
        <Link href="Members">
          <a>artists</a>
        </Link>

        <div className={styles.grid}>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          210 go spurs go!
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
